version: '3.7'

services:
  server:
    image: nginx
    container_name: app-nginx
    volumes:
      - .:/var/www/html
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8000:80
    networks:
      - backend

  api:
    build: .docker/php
    container_name: app-php
    volumes:
      - .:/var/www/html:rw
    networks:
      - backend

  mysql:
    image: mysql:5.7
    container_name: app-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: potential
      MYSQL_USER: potential
      MYSQL_PASSWORD: potential
      MYSQL_ROOT_PASSWORD: potential
    volumes:
      - .docker/dbdata:/var/lib/mysql
    networks:
      - backend

networks:
  backend: